### PR TITLE
Allow numbers in gzip file extensions

### PR DESCRIPTION
**Pull request by cyruskazemi**

### CODE REVIEW

**Review by nitaigao — APPROVED** [review]

**Comment by cyruskazemi** [comment]
@nitaigao thanks for the approval. I don't have write access so can you merge?

**Comment by nitaigao** [comment]
@cyruskazemi Thanks for the help :)

**Comment by cyruskazemi** [comment]
@nitaigao My pleasure. Can you publish to npm as well?

**Comment by cyruskazemi** [comment]
@nitaigao bump on the last comment. Would you mind publishing to npm?

**Pull request merged**
